services:
  db:
    container_name: pg_db
    image: postgres:16
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  task_app:
    build:
      context: .
      dockerfile: task_dockerfile
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@pg_db:5432/tasks?schema=public'
      RABBITMQ_URL: 'amqp://guest:guest@my-rabbitmq:5672/'
    ports:
      - '5000:5000'
    depends_on:
      - db
      - rabbit
    command: ['sh', '-c', 'npm run start:dev']

  auth_app:
    build:
      context: .
      dockerfile: auth_dockerfile
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@pg_db:5432/tasks?schema=public'
      RABBITMQ_URL: 'amqp://guest:guest@my-rabbitmq:5672/'
    ports:
      - '5001:5001'
    depends_on:
      - db
      - rabbit
    command: ['sh', '-c', 'npm run start:dev']

  rabbit:
    image: 'rabbitmq:3-management'
    hostname: my-rabbitmq
    environment:
      - PATH=/opt/rabbitmq/sbin:/opt/erlang/bin:/opt/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ERLANG_INSTALL_PATH_PREFIX=/opt/erlang
      - OPENSSL_INSTALL_PATH_PREFIX=/opt/openssl
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq
      - RABBITMQ_VERSION=3.13.6
      - RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
      - RABBITMQ_HOME=/opt/rabbitmq
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: no
    labels:
      org.opencontainers.image.ref.name: ubuntu
      org.opencontainers.image.version: '22.04'
    runtime: runc

volumes:
  postgres_data:
  rabbitmq_data:
